api/urls.py
from django.urls import path
from api.views import CategoriasViewSet
from rest_framework.routers import DefaultRouter

from api.views import *

app_name = 'api'

router = DefaultRouter(trailing_slash=False)
router.register('categorias', CategoriasViewSet, basename='categorias')
router.register('noticias', NoticiasViewSet, basename='noticias')
urlpatterns = []
urlpatterns += router.urls

noticias/urls.py
from django.urls import path
from noticias.views import publicar_noticia

app_name = 'noticias'
urlpatterns = [
    path('publicar/', publicar_noticia, name='publicar'),
]

portal_noticias/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('contato', contato, name='contato'),
    path('noticias/', include('noticias.urls', namespace='noticia')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]

api/models.py
from django.db import models

# Create your models here.

base/models.py
from django.db import models

ESCOLHA = [
    ('alta', 'Alta'),
    ('media', 'Média'),
    ('baixa', 'Baixa'),
]

class TimeStampedModel(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Contato(TimeStampedModel):
    nome = models.CharField('Nome', max_length=50)
    email = models.EmailField('E-mail')
    prioridade = models.CharField('Prioridade', max_length=6,  choices=ESCOLHA)
    mensagem = models.TextField('Mensagem')
    lido = models.BooleanField('Lido', default=False, blank=True)

    def __str__(self):
        return self.nome
    
class Categorias(TimeStampedModel):
    nome = models.CharField('Nome', max_length=50)
    descricao = models.CharField('Descrição', max_length=300)

    def __str__(self):
        return self.nome

noticias/models.py
from django.db import models
from base.models import TimeStampedModel, Categorias

class Noticias(TimeStampedModel):
    titulo = models.CharField('Título', max_length=300)
    categoria  = models.ForeignKey(Categorias, on_delete=models.SET_DEFAULT, default=6)
    descricao = models.TextField('Noticia')

    def __str__(self):
        return self.titulo

base/forms.py
from django import forms
from base.models import Contato

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'email', 'prioridade', 'mensagem']
        widgets = {
            'nome': forms.TextInput(
                attrs= {
                    'placeholder':'Informe o nome Completo'
                }
            ),
            'email': forms.TextInput(
                attrs= {
                    'placeholder':'Informe o E-mail'
                }
            ),
            'mensagem': forms.Textarea(
                attrs= {
                    'placeholder':'Insira a Mensagem'
                }
            ),
        }

noticias/forms.py
from django import forms
from noticias.models import Noticias
from base.models import Categorias

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticias
        fields = ['titulo', 'categoria', 'descricao']
        widgets = {
            'titulo': forms.TextInput(
                attrs = {
                    'placeholder':'Informe o Titulo da Noticia'
                }
            ),
            'descricao': forms.Textarea(
                attrs = {
                    'placeholder':'Escreva aqui o conteúdo da Noticia'
                }
            ),
        }
   

api/views.py
from rest_framework.decorators import api_view
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from base.models import Categorias
from noticias.models import Noticias

from rest_framework.viewsets import ModelViewSet
from api.serializers import CategoriasSerializer, NoticiasSerializer

class CategoriasViewSet(ModelViewSet):
    serializer_class = CategoriasSerializer
    queryset = Categorias.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

class NoticiasViewSet(ModelViewSet):
    serializer_class = NoticiasSerializer
    queryset = Noticias.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

base/views.py
from django.shortcuts import render
from base.models import Contato
from base.forms import ContatoForm
from noticias.models import Noticias

def inicio(request):
    noticias = Noticias.objects.all()
    qtda_noticias = len(noticias)
    print(qtda_noticias)
    contexto = {
        'qtda_noticias': qtda_noticias,
        'noticias': noticias,
    }

    return render(request,'index.html', contexto)

def contato(request):
    sucesso = False
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        'form': form,
        'sucesso': sucesso,
    }
    return render(request, 'contato.html', contexto)    

noticias/views.py
from django.shortcuts import render
from noticias.models import Noticias
from noticias.forms import NoticiaForm

def publicar_noticia(request):
    sucesso = False
    form = NoticiaForm(request.POST or None)
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        'form': form,
        'sucesso': sucesso,
    }
    return render(request, 'pub_noticia.html', contexto)

base/templates/contato.html
{%extends 'index.html'%}
{% load bootstrap5 %}
 
{%block title%}
  Contato
{%endblock%}

{%block container%}
<div class="container">
  <main>
    <div class="p-4 p-md-5 mb-4  text-white rounded bg-dark">
      <div class="row justify-content-space-between gy-4">
        <div class="col-6 col-md-auto">
          <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" fill="currentColor" class="bi bi-headset" viewBox="0 0 16 16">
            <path d="M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5z"/>
          </svg>
        </div>
        <div class="col col-md-auto">
          <h1 class= "fst-italic ps-4">Fale Conosco</h1>
        </div>
      </div>  
    </div>
    {% if sucesso %}
      <p class="alert alert-success"> Mensagem Enviada com Sucesso!</p>
    {% else %} 

      <div class="row g-5">
                
        <div class="col-md-7 col-lg-8 mx-auto">
          <form class="needs-validation" action="" method="POST" novalidate>
            <div class="row g-3 m-3 p-3 border border-1 bg-dark text-white">
              {% csrf_token %}
              {% bootstrap_form form %}           

            <hr class="my-4">

            <button class="w-100 btn btn-primary btn-lg" type="submit">Enviar</button>
          </form>
        </div>
      </div>
    {% endif%}
  </main>
  {%endblock%}

base/templates/index.html
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
  <title>{%block title%}Portal de Noticias{%endblock%}</title>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
</head>
<body>
  <div class="container">
    <header class="blog-header py-3">
      {%block header%}
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">    
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe2" viewBox="0 0 16 16">
            <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855-.143.268-.276.56-.395.872.705.157 1.472.257 2.282.287V1.077zM4.249 3.539c.142-.384.304-.744.481-1.078a6.7 6.7 0 0 1 .597-.933A7.01 7.01 0 0 0 3.051 3.05c.362.184.763.349 1.198.49zM3.509 7.5c.036-1.07.188-2.087.436-3.008a9.124 9.124 0 0 1-1.565-.667A6.964 6.964 0 0 0 1.018 7.5h2.49zm1.4-2.741a12.344 12.344 0 0 0-.4 2.741H7.5V5.091c-.91-.03-1.783-.145-2.591-.332zM8.5 5.09V7.5h2.99a12.342 12.342 0 0 0-.399-2.741c-.808.187-1.681.301-2.591.332zM4.51 8.5c.035.987.176 1.914.399 2.741A13.612 13.612 0 0 1 7.5 10.91V8.5H4.51zm3.99 0v2.409c.91.03 1.783.145 2.591.332.223-.827.364-1.754.4-2.741H8.5zm-3.282 3.696c.12.312.252.604.395.872.552 1.035 1.218 1.65 1.887 1.855V11.91c-.81.03-1.577.13-2.282.287zm.11 2.276a6.696 6.696 0 0 1-.598-.933 8.853 8.853 0 0 1-.481-1.079 8.38 8.38 0 0 0-1.198.49 7.01 7.01 0 0 0 2.276 1.522zm-1.383-2.964A13.36 13.36 0 0 1 3.508 8.5h-2.49a6.963 6.963 0 0 0 1.362 3.675c.47-.258.995-.482 1.565-.667zm6.728 2.964a7.009 7.009 0 0 0 2.275-1.521 8.376 8.376 0 0 0-1.197-.49 8.853 8.853 0 0 1-.481 1.078 6.688 6.688 0 0 1-.597.933zM8.5 11.909v3.014c.67-.204 1.335-.82 1.887-1.855.143-.268.276-.56.395-.872A12.63 12.63 0 0 0 8.5 11.91zm3.555-.401c.57.185 1.095.409 1.565.667A6.963 6.963 0 0 0 14.982 8.5h-2.49a13.36 13.36 0 0 1-.437 3.008zM14.982 7.5a6.963 6.963 0 0 0-1.362-3.675c-.47.258-.995.482-1.565.667.248.92.4 1.938.437 3.008h2.49zM11.27 2.461c.177.334.339.694.482 1.078a8.368 8.368 0 0 0 1.196-.49 7.01 7.01 0 0 0-2.275-1.52c.218.283.418.597.597.932zm-.488 1.343a7.765 7.765 0 0 0-.395-.872C9.835 1.897 9.17 1.282 8.5 1.077V4.09c.81-.03 1.577-.13 2.282-.287z"/>
          </svg>         
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'noticias:publicar' %}">Publicar Noticia</a>
        </div>
        <div class="col-4 text-center">
          <a class="blog-header-logo text-dark text-decoration-none" href="{%url 'inicio'%}"><h1>Portal de Noticias</h1></a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'contato' %}">Contato</a>
        </div>
      </div>
      {%endblock%}
    </header>

    <div class="nav-scroller py-1 mb-2">
      {%block menu%}
      <nav class="nav d-flex justify-content-between">
        {% for categoria in categorias %}
        <a class="p-2 link-secondary" href="#" style="text-decoration: none;">{{categoria.nome}}</a>
        {% endfor %}
      </nav>
      {%endblock%}
    </div>
  </div>

  <main class="container">
    {%block container%}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
      <div class="row mb-2">
        <div class="col-md-6 px-0">
          <h1 class="display-4 fst-italic">Noticias do Dia</h1>
          <p class="lead my-2">Fique informado com as principais noticias do seu dia-a-dia por aqui.</p>
        </div>
      </div>
    </div>
    <div class="row mb-2">
      {% if qtda_noticias == 0%}
      <div class="col-md-12 text-center">
        <p><strong>Sem Noticias no momento</strong></p>
      </div>
      {% else %}
      {%for noticia in noticias%}
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">{{noticia.categoria}}</strong>
              <h3 class="mb-0">{{noticia.titulo}}</h3>
              <div class="mb-1 text-muted">{{noticia.atualizado_em|date:'d/m/Y H:i'}}</div>
              <p class="card-text mb-auto">{{noticia.descricao}}</p>
              <a href="#" class="stretched-link" title={{noticia.titulo}} aria-disabled="true" data-bs-toggle="modal" data-bs-target="#loginModal">Continue lendo...</a>
            </div>
          </div>
        </div>
      {% endfor %}
      {% endif %}
    </div>
    {%endblock%}
  </main>
  {%block footer%}
   
    <footer class="mt-4 p-0 text-white text-center text-small bg-dark">
      <p>Atividade de Django para o curso de Desenvolvedor em Python Completo da <a href="https://promo.ultima.school/python/">Ultima School</a>
      <p class="pb-4 m-0 text-reset">
        <a href="{%url 'inicio'%}" style="text-decoration:none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
            <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
          </svg>
          Voltar a Pagina Inicial
        </a>
      </p>
    </footer>
    {%endblock%}
</body>
</html>

noticias/templates/pub_noticia.html
{%extends 'index.html'%}
{% load bootstrap5 %}
 
{%block title%}
  Contato
{%endblock%}

{%block container%}
<div class="container">
  <main>
    <div class="p-4 p-md-5 mb-4  text-white rounded bg-dark">
      <div class="row justify-content-space-between gy-4">
        <div class="col-6 col-md-auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="80" height="80" fill="currentColor" class="bi bi-headset" viewBox="0 0 16 16">
            <path d="M17.263 2.177a1.75 1.75 0 0 1 2.474 0l2.586 2.586a1.75 1.75 0 0 1 0 2.474L19.53 10.03l-.012.013L8.69 20.378a1.753 1.753 0 0 1-.699.409l-5.523 1.68a.748.748 0 0 1-.747-.188.748.748 0 0 1-.188-.747l1.673-5.5a1.75 1.75 0 0 1 .466-.756L14.476 4.963ZM4.708 16.361a.26.26 0 0 0-.067.108l-1.264 4.154 4.177-1.271a.253.253 0 0 0 .1-.059l10.273-9.806-2.94-2.939-10.279 9.813ZM19 8.44l2.263-2.262a.25.25 0 0 0 0-.354l-2.586-2.586a.25.25 0 0 0-.354 0L16.061 5.5Z"></path>
          </svg>
        </div>
        <div class="col col-md-auto">
          <h1 class= "fst-italic ps-4">Publique uma Noticia</h1>
        </div>
      </div>  
    </div>
    {% if sucesso %}
      <p class="alert alert-success"> Noticia publicada com Sucesso!</p>
    {% else %} 

      <div class="row g-5">
                
        <div class="col-md-7 col-lg-8 mx-auto">
          <form class="needs-validation" action="" method="POST" novalidate>
            <div class="row g-3 m-3 p-3 border border-1 bg-dark text-white">
              {% csrf_token %}
              {% bootstrap_form form %}           

            <hr class="my-4">

            <button class="w-100 btn btn-outline-primary btn-lg" type="submit">Enviar</button>
          </form>
        </div>
      </div>
    {% endif%}
  </main>
  {%endblock%}